//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.DataAccess.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.DataAccess.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Property.
    /// </summary>
    internal static string Controls_ConnectionStringAdvancedOptionsWindow_DataGridTextColumn_Header_Property {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringAdvancedOptionsWindow_DataGridTextColumn_Header_Property" +
                    "", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Value.
    /// </summary>
    internal static string Controls_ConnectionStringAdvancedOptionsWindow_DataGridTextColumn_Header_Value {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringAdvancedOptionsWindow_DataGridTextColumn_Header_Value", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Search....
    /// </summary>
    internal static string Controls_ConnectionStringBuilder_Search_WaterMark {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringBuilder_Search_WaterMark", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Advanced....
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_Button_Content_Advanced {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Button_Content_Advanced", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Refresh.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_Button_Content_Refresh {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Button_Content_Refresh", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Test connection.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_Button_Content_TestConnection {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Button_Content_TestConnection", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Log on to the server.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_GroupBox_Header_LogOnToTheServer {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_GroupBox_Header_LogOnToTheServer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Database:.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_Label_Content_Database {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_Database", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Password.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_Label_Content_Password {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_Password", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Provider:.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_Label_Content_Provider {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_Provider", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Server:.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_Label_Content_Server {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_Server", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to User name.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_Label_Content_UserName {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_UserName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Use SQL Server Authentication.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_RadioButton_Content_UseSQLServerAuthentication {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_RadioButton_Content_UseSQLServerAuthenticatio" +
                    "n", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Use Windows Authentication.
    /// </summary>
    internal static string Controls_ConnectionStringEditWindow_RadioButton_Content_UseWindowsAuthentication {
        get {
            return ResourceManager.GetString("Controls_ConnectionStringEditWindow_RadioButton_Content_UseWindowsAuthentication", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select provider.
    /// </summary>
    internal static string Controls_DbConnectionProviderList_Title {
        get {
            return ResourceManager.GetString("Controls_DbConnectionProviderList_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Refresh.
    /// </summary>
    internal static string Controls_DbConnectionProviderListWindow_Button_Content_Refresh {
        get {
            return ResourceManager.GetString("Controls_DbConnectionProviderListWindow_Button_Content_Refresh", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Change....
    /// </summary>
    internal static string Controls_DbProviderControl_Button_Content_Change {
        get {
            return ResourceManager.GetString("Controls_DbProviderControl_Button_Content_Change", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Change....
    /// </summary>
    internal static string Controls_DbProviderPicker_Button_Content_Change {
        get {
            return ResourceManager.GetString("Controls_DbProviderPicker_Button_Content_Change", resourceCulture);
        }
    }
}
